[package]
name = "rshui"
version = "0.0.0"
authors = ["SchokiCoder <afschoknecht@gmail.com>"]
repository = "https://github.com/SchokiCoder/rshui"
edition = "2021"
license = "BSD-3-Clause"
publish = false
