header = "Example config\n"
entry_menu_prefix =   "> ["
entry_menu_postfix =  "]"
entry_shell_prefix =  "> "
entry_shell_postfix = ""
entry_shellsession_prefix =  "> <"
entry_shellsession_postfix = ">"

[colors.entry.fg]
active = false
r = 255
g = 255
b = 255	

[colors.entry.bg]
active = false
r = 30
g = 30
b = 30	

[colors.entry_hover.fg]
active = true
r = 0
g = 0
b = 0	

[colors.entry_hover.bg]
active = true
r = 255
g = 255
b = 255

[keys]
execute = "L"

[menus.test_chamber]
title = """
Test chamber
------------"""

[[menus.test_chamber.entries]]
caption = "stdout"
content = {Shell = "echo \"lies\""}

[[menus.test_chamber.entries]]
caption = "stderr"
content = {Shell = "cc"}

[[menus.test_chamber.entries]]
caption = "vi ~/temp"
content = {ShellSession = "vi ~/temp"}

[menus.main]
title = """
Main Menu
---------"""

[[menus.main.entries]]
caption = "Show current user"
content = {Shell = "echo \"$USER\""}

[[menus.main.entries]]
caption = "Test chamber"
content = {Menu = "test_chamber"}

[[menus.main.entries]]
caption = "Clear ~/temp"
content = {Shell = "echo \"\" > ~/temp"}

